apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/flask-apps.git
    targetRevision: main
    path: manifests/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
