apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SHIVAYADAV99/flask-apps.git
    targetRevision: dev
    path: manifests/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
