apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SHIVAYADAV99/flask-apps.git
    targetRevision: main
    path: manifests/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
