apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/flask-apps.git
    targetRevision: dev
    path: manifests/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
