name: CI/CD - Flask App (DockerHub + ArgoCD GitOps)

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: flask-app

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: set-tag
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  update-manifests:
    name: Update K8s Manifests (GitOps)
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Manifest Image
        run: |
          NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}"
          echo "Updating image to: $NEW_IMAGE"

          # make sure directory name is correct (manifests)
<<<<<<< HEAD
           sed -i "s|image:.*|image: $NEW_IMAGE|g" mainfests/deployment.yaml
=======
          sed -i "s|image:.*|image: $NEW_IMAGE|g" mainfests/deployment.yaml
>>>>>>> 63a51cca150e243e37556ecde5f2cb6895a19b60

          git checkout -b update-image-${{ github.run_id }}
          git add mainfests/deployment.yaml
          git commit -m "Update image to $NEW_IMAGE"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-image-${{ github.run_id }}
          title: "Update image to latest build"
          body: "This PR updates the Kubernetes manifest to use the latest image."
          labels: automated

